# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'moneyiOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moneyiOS
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'BXProgressHUD'
  #pod 'ChameleonFramework/Swift'
end
