# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'moneyiOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moneyiOS
  pod 'Alamofire', '4.0.0'
  pod 'SnapKit', '3.0.1'
  pod 'Kingfisher', '3.1.0'
  pod 'RappleProgressHUD', '2.0.4'
  #pod 'EVReflection', '2.46.0'
  pod 'Bugly', '2.4.0'
  pod 'JASON', '3.0'
  #pod 'KSCrash'
  #pod 'ChameleonFramework/Swift'
end
